[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
allow_paths = ["../vendor"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=../vendor/openzeppelin/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
