[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
allow_paths = ["../vendor"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@onchain-id/solidity/=../vendor/onchainid/",
    "forge-std/=lib/forge-std/src/",
    "erc3643/=../vendor/erc3643/",
    "onchainid/=../vendor/onchainid/"
]

[profile.novir]
via_ir = false
